version: 1
datastore:
  filename: /data/data.json
scheduler:
  interval: 5
eventstore:
  shots:
    url: http://dashboard/storage/storage/shots
  penalties:
    url: http://dashboard/storage/storage/penalties