version: 1
datastore:
  user: hockey_user
  password: hockey_pass
  hostname: db        
  port: 3306          
  db: hockey_storage

events:
  hostname: kafka
  port: 29092
  topic: events
  group_id: storage_group